### ISSUE TITLE
F# support

### ISSUE THREAD

**Issue by drhumlen** [dima74/intellij-indent-rainbow#12] opened 2020-04-04 13:28 UTC
F# doesn't seem to work with the plugin. Would it be possible to have it look at indentation only and colorize based on that? F# shouldn't be different from any other language in that regard?

**Comment by dima74** [comment] 2020-04-04 14:15
@drhumlen thank you for reporting! I will take a look. Could you please specify your plugin version? Also please try to switch to [simple highlighter](https://raw.githubusercontent.com/dima74/intellij-indent-rainbow/master/assets/choose-simple-annotator.png) as a workaround (though I am not sure if it works with F#)

**Comment by drhumlen** [comment] 2020-04-04 23:19
I've tried all highlighter types, including `Simple, incremental`.

I'm using version 1.4.1 of the plugin.

And:
JetBrains Rider 2020.1 EAP 7
Build #RD-201.6668.91, built on April 2, 2020
Rider EAP User
Expiration date: May 2, 2020
Runtime version: 11.0.6+8-b765.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
.NET Core 3.1.3
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1450M
Cores: 8

**Comment by dima74** [comment] 2020-04-06 19:21
Ok, I reproduced the issue. I think ideally it should be fixed on [Rider side](https://youtrack.jetbrains.com/issue/RIDER-21994) because some other plugins are also affected, [for example rainbow-brackets](https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/186). But I will try to implement some workaround

**Comment by dima74** [comment] 2020-04-07 09:45
@drhumlen could you please try latest plugin version (1.4.2)?

**Comment by drhumlen** [comment] 2020-04-08 08:51
@dima74 : It seems to work now 😄 Nice!

It seems to be a little flaky sometimes though. I need to do some more testing.

**Comment by dima74** [comment] 2020-05-22 10:50
@drhumlen Hello! Can we close this issue or is there anything related to F# I could improve?

**Comment by drhumlen** [comment] 2020-05-30 10:13
Yes. I think it's working mostly as intended now.

There's still some room for improvement when it comes to what defines an indentation level though. In F# the indentation can often be inconsistent and not always a perfect X * tabSize. I don't have a good suggestion for that. But the indentation guides in Rider are usually spot on. Perhaps it's possible to colorize the already existing indentation guides instead of rainbow'ing the whole gutter? 🤔

**Closed** 2020-05-30 10:13 UTC
Labels: bug

**Comment by dima74** [comment] 2020-05-30 11:24
@drhumlen thanks for the suggestion, I think it is possible. Could you please provide code sample and/or screenshot (with current plugin behaviour) for me to better understand use case
