### ISSUE TITLE
Disagreement between Indent Rainbow and PhpStorm with Twig

### ISSUE THREAD

**Issue by YetAnotherDevWannabe** [dima74/intellij-indent-rainbow#30] opened 2021-06-20 14:19 UTC
When using Twig, indent rainbow and phpStorm seem to not agree on the correct indentation :

![IndentRainbowTwig](https://user-images.githubusercontent.com/6054349/122677500-cdc53680-d1e2-11eb-9fc4-14ea4b997b59.jpg)
This is after re-formating my code. Apparently, for phpStorm inside a twig block you need to indent, but not for IR.

This is what IR wants :

![IndentRainbowTwig2](https://user-images.githubusercontent.com/6054349/122677557-23014800-d1e3-11eb-8c5b-e13e13891909.jpg)

**Comment by dima74** [comment] 2021-11-11 12:19
Thanks for report and sorry for long response.

> Apparently, for phpStorm inside a twig block you need to indent

Which formatter do you use (built-in or some external one)? I can't reproduce it with default PhpStorm settings:

<img src="https://user-images.githubusercontent.com/6505554/141296727-929f9c11-0591-4335-94cf-3cd8514e1765.gif" width="50%">

**Comment by YetAnotherDevWannabe** [comment] 2021-11-11 18:29
Hi,

I believe I used a custom one at the time. Since then I had to switch to
vscode sadly so I don't know if I still have the problem.

Le jeu. 11 nov. 2021 à 13:19, Dmitry Murzin ***@***.***> a
écrit :

**Comment by dima74** [comment] 2022-03-14 10:13
Should be fixed in [v2.0.1](https://plugins.jetbrains.com/plugin/13308-indent-rainbow/versions/stable/161785) where we started to use indent-based highlighter by default

**Closed by dima74** 2022-03-14 10:13 UTC
